[pytest]
markers =
    valid: mark a test as valid scenario
    smoke: mark a test as smoke scenario
    security: mark a test as security scenario
    positive: mark a test as positive scenario
    negative: mark a test as negative scenario
    edge: mark a test as edge scenario
    regression: mark a test as regression scenario
    boundary: mark a test as boundary scenario
    performance: mark a test as performance scenario
    flexibility: mark a test as flexibility scenario
    invalid: mark a test as invalid scenario
