# ********RoostGPT********
"""
Test generated by RoostGPT for test pythonLangTest using AI Type Open AI and AI Model gpt-4o

ROOST_METHOD_HASH=sort_4b1ab3987d
ROOST_METHOD_SIG_HASH=sort_3ecc0d0631


Scenario 1: Sort a Small File with Default Sorting
Details:
  TestName: test_sort_small_file_default
  Description: Verify that the function correctly sorts a small file using the default sorting order when no sort key is provided.
Execution:
  Arrange: Create a small text file with unsorted lines. Initialize the `FileSplitter` and `FileMerger` classes.
  Act: Invoke the `sort` method with the filename of the small file and no sort key.
  Assert: Check that the output file is sorted in ascending order.
Validation:
  Rationalize the importance of ensuring that the function can handle small files and default sorting, which is a basic requirement for any sorting function.

Scenario 2: Sort a Large File with a Custom Sort Key
Details:
  TestName: test_sort_large_file_custom_key
  Description: Ensure that the function can handle large files and correctly apply a custom sort key.
Execution:
  Arrange: Create a large text file with unsorted lines. Define a custom sort key function. Initialize the `FileSplitter` and `FileMerger` classes.
  Act: Invoke the `sort` method with the filename of the large file and the custom sort key.
  Assert: Verify that the output file is sorted according to the custom key.
Validation:
  Rationalize the importance of supporting custom sort keys for flexibility in sorting criteria, which is crucial for diverse business needs.

Scenario 3: Handle Empty File Gracefully
Details:
  TestName: test_sort_empty_file
  Description: Check that the function handles an empty file without errors and produces an empty output file.
Execution:
  Arrange: Create an empty text file. Initialize the `FileSplitter` and `FileMerger` classes.
  Act: Invoke the `sort` method with the filename of the empty file.
  Assert: Confirm that the output file is also empty.
Validation:
  Rationalize the importance of gracefully handling edge cases like empty files to ensure robustness and prevent runtime errors.

Scenario 4: Sort File with Identical Lines
Details:
  TestName: test_sort_identical_lines
  Description: Verify that the function correctly processes a file where all lines are identical, resulting in an unchanged order.
Execution:
  Arrange: Create a text file where all lines are identical. Initialize the `FileSplitter` and `FileMerger` classes.
  Act: Invoke the `sort` method with the filename of the file containing identical lines.
  Assert: Ensure that the output file maintains the same order as the input.
Validation:
  Rationalize the importance of handling files with identical lines to ensure consistent behavior and output integrity.

Scenario 5: Sort File with Mixed Data Types
Details:
  TestName: test_sort_mixed_data_types
  Description: Ensure that the function can sort a file containing lines with mixed data types when a suitable sort key is provided.
Execution:
  Arrange: Create a text file with lines containing mixed data types (e.g., strings and numbers). Define a sort key that can handle these types. Initialize the `FileSplitter` and `FileMerger` classes.
  Act: Invoke the `sort` method with the filename of the mixed data type file and the sort key.
  Assert: Verify that the output file is sorted correctly according to the provided key.
Validation:
  Rationalize the importance of supporting mixed data types to accommodate diverse data sets and enhance the function's versatility.

"""

# ********RoostGPT********
import pytest
import os
from external_sort import ExternalSort
from external_sort import FileSplitter, FileMerger, NWayMerge

@pytest.fixture
def setup_external_sort():
    # TODO: Set the appropriate block size for your test cases
    block_size = 1024
    return ExternalSort(block_size)

@pytest.mark.valid
def test_sort_small_file_default(setup_external_sort):
    # Arrange
    filename = "small_file.txt"
    with open(filename, "w") as f:
        f.write("banana\napple\ncherry\n")

    # Act
    setup_external_sort.sort(filename)

    # Assert
    with open(filename + ".out", "r") as f:
        lines = f.readlines()
    assert lines == ["apple\n", "banana\n", "cherry\n"]

    # Cleanup
    os.remove(filename)
    os.remove(filename + ".out")

@pytest.mark.regression
def test_sort_large_file_custom_key(setup_external_sort):
    # Arrange
    filename = "large_file.txt"
    with open(filename, "w") as f:
        for i in range(1000, 0, -1):
            f.write(f"{i}\n")

    custom_sort_key = lambda x: int(x.strip())

    # Act
    setup_external_sort.sort(filename, sort_key=custom_sort_key)

    # Assert
    with open(filename + ".out", "r") as f:
        lines = f.readlines()
    assert lines == [f"{i}\n" for i in range(1, 1001)]

    # Cleanup
    os.remove(filename)
    os.remove(filename + ".out")

@pytest.mark.negative
def test_sort_empty_file(setup_external_sort):
    # Arrange
    filename = "empty_file.txt"
    open(filename, "w").close()

    # Act
    setup_external_sort.sort(filename)

    # Assert
    with open(filename + ".out", "r") as f:
        lines = f.readlines()
    assert lines == []

    # Cleanup
    os.remove(filename)
    os.remove(filename + ".out")

@pytest.mark.valid
def test_sort_identical_lines(setup_external_sort):
    # Arrange
    filename = "identical_lines.txt"
    with open(filename, "w") as f:
        f.write("same\nsame\nsame\n")

    # Act
    setup_external_sort.sort(filename)

    # Assert
    with open(filename + ".out", "r") as f:
        lines = f.readlines()
    assert lines == ["same\n", "same\n", "same\n"]

    # Cleanup
    os.remove(filename)
    os.remove(filename + ".out")

@pytest.mark.valid
def test_sort_mixed_data_types(setup_external_sort):
    # Arrange
    filename = "mixed_data_types.txt"
    with open(filename, "w") as f:
        f.write("100\napple\n50\nbanana\n")

    custom_sort_key = lambda x: (x.isdigit(), x.strip())

    # Act
    setup_external_sort.sort(filename, sort_key=custom_sort_key)

    # Assert
    with open(filename + ".out", "r") as f:
        lines = f.readlines()
    assert lines == ["50\n", "100\n", "apple\n", "banana\n"]

    # Cleanup
    os.remove(filename)
    os.remove(filename + ".out")
