# ********RoostGPT********
"""
Test generated by RoostGPT for test pythonLangTest using AI Type Open AI and AI Model gpt-4o

ROOST_METHOD_HASH=selection_sort_efa24ec707
ROOST_METHOD_SIG_HASH=selection_sort_c545f36590


Scenario 1: Sorting an Already Sorted List
Details:
  TestName: test_sorted_list
  Description: Verify that the function correctly identifies an already sorted list and returns it unchanged.
Execution:
  Arrange: Prepare a list that is already sorted in ascending order, e.g., [1, 2, 3, 4, 5].
  Act: Invoke the selection_sort function with the sorted list as the parameter.
  Assert: Check that the returned list is identical to the input list, [1, 2, 3, 4, 5].
Validation:
  This test ensures that the function does not alter a list that is already sorted, maintaining its integrity and demonstrating efficiency by avoiding unnecessary operations.

Scenario 2: Sorting a List with Duplicate Elements
Details:
  TestName: test_list_with_duplicates
  Description: Confirm that the function can handle lists with duplicate elements and sorts them correctly.
Execution:
  Arrange: Create a list containing duplicate elements, such as [4, 5, 3, 4, 1, 1].
  Act: Call the selection_sort function with the list containing duplicates.
  Assert: Verify that the returned list is sorted in ascending order, [1, 1, 3, 4, 4, 5].
Validation:
  This test is crucial to ensure that the function handles duplicates properly, maintaining the correct order and count of elements.

Scenario 3: Sorting a List with Negative Numbers
Details:
  TestName: test_list_with_negatives
  Description: Ensure that the function can correctly sort a list containing negative numbers.
Execution:
  Arrange: Prepare a list with negative numbers, e.g., [-3, -1, -7, -4, -5].
  Act: Execute the selection_sort function with the negative number list.
  Assert: Confirm that the output list is sorted in ascending order, [-7, -5, -4, -3, -1].
Validation:
  This test validates the function's ability to handle and correctly sort negative integers, which is essential for comprehensive sorting functionality.

Scenario 4: Sorting an Empty List
Details:
  TestName: test_empty_list
  Description: Check that the function correctly handles an empty list by returning it unchanged.
Execution:
  Arrange: Use an empty list as input, [].
  Act: Pass the empty list to the selection_sort function.
  Assert: Ensure that the function returns an empty list, [].
Validation:
  This test is important to confirm that the function can gracefully handle edge cases like empty inputs without errors.

Scenario 5: Sorting a List with a Single Element
Details:
  TestName: test_single_element_list
  Description: Verify that the function correctly processes a list with a single element, returning it unchanged.
Execution:
  Arrange: Create a list with a single element, e.g., [42].
  Act: Invoke the selection_sort function with the single-element list.
  Assert: Check that the returned list is the same as the input, [42].
Validation:
  This test ensures that the function can handle minimal input sizes correctly, which is essential for robustness.

Scenario 6: Sorting a List with All Identical Elements
Details:
  TestName: test_identical_elements_list
  Description: Ensure that the function can handle a list where all elements are identical.
Execution:
  Arrange: Prepare a list where all elements are the same, such as [7, 7, 7, 7].
  Act: Call the selection_sort function with the identical elements list.
  Assert: Verify that the returned list remains unchanged, [7, 7, 7, 7].
Validation:
  This test checks the function's ability to handle uniform data without unnecessary operations, ensuring efficiency and correctness.

"""

# ********RoostGPT********
import pytest
from selection_sort import selection_sort

class Test_SelectionSortSelectionSort:

    @pytest.mark.positive
    def test_sorted_list(self):
        # Arrange
        sorted_list = [1, 2, 3, 4, 5]
        # Act
        result = selection_sort(sorted_list)
        # Assert
        assert result == [1, 2, 3, 4, 5]

    @pytest.mark.positive
    def test_list_with_duplicates(self):
        # Arrange
        list_with_duplicates = [4, 5, 3, 4, 1, 1]
        # Act
        result = selection_sort(list_with_duplicates)
        # Assert
        assert result == [1, 1, 3, 4, 4, 5]

    @pytest.mark.positive
    def test_list_with_negatives(self):
        # Arrange
        list_with_negatives = [-3, -1, -7, -4, -5]
        # Act
        result = selection_sort(list_with_negatives)
        # Assert
        assert result == [-7, -5, -4, -3, -1]

    @pytest.mark.positive
    def test_empty_list(self):
        # Arrange
        empty_list = []
        # Act
        result = selection_sort(empty_list)
        # Assert
        assert result == []

    @pytest.mark.positive
    def test_single_element_list(self):
        # Arrange
        single_element_list = [42]
        # Act
        result = selection_sort(single_element_list)
        # Assert
        assert result == [42]

    @pytest.mark.positive
    def test_identical_elements_list(self):
        # Arrange
        identical_elements_list = [7, 7, 7, 7]
        # Act
        result = selection_sort(identical_elements_list)
        # Assert
        assert result == [7, 7, 7, 7]
