# ********RoostGPT********
"""
Test generated by RoostGPT for test testingGemini-1 using AI Type Gemini AI and AI Model gemini-2.0-flash-lite

ROOST_METHOD_HASH=quick_sort_657b26bba5
ROOST_METHOD_SIG_HASH=quick_sort_ead3a89d01


Scenario 1: Sorting a list of positive integers
Details:
  TestName: test_sort_positive_integers
  Description: Verifies the correct sorting of a list containing positive integer values.
Execution:
  Arrange: Prepare a list of positive integers in a random order, such as `[3, 1, 4, 1, 5, 9, 2, 6]`.
  Act: Call the `quick_sort` function with the prepared list as input.
  Assert: Check if the returned list is sorted in ascending order. Verify this by comparing it to the output of `sorted()` applied to the same input list.
Validation:
  This test ensures the core functionality of the quick sort algorithm by verifying its ability to sort a typical numerical dataset.

Scenario 2: Sorting a list of negative integers
Details:
  TestName: test_sort_negative_integers
  Description: Tests the function's ability to handle negative integer values and sort them correctly.
Execution:
  Arrange: Prepare a list of negative integers, such as `[-3, -1, -4, -1, -5, -9, -2, -6]`.
  Act: Call the `quick_sort` function with the negative integer list.
  Assert: Assert that the function returns a list sorted in ascending order. This can be done by comparing against the output of `sorted()` applied to the input list.
Validation:
  This test validates the algorithm's correctness when dealing with negative values, covering a different range of numbers than the positive integer test.

Scenario 3: Sorting a list containing both positive and negative integers
Details:
  TestName: test_sort_mixed_positive_negative_integers
  Description: Evaluates the sorting of a list containing a mix of positive and negative integer values.
Execution:
  Arrange: Create a list with both positive and negative integers, such as `[-2, 1, -5, 4, 0, -1, 3]`.
  Act: Invoke the `quick_sort` function, passing the mixed-integer list.
  Assert: Confirm that the output list is sorted correctly in ascending order. Compare with the result of calling `sorted()` on the original list.
Validation:
  This test combines the scenarios from tests 1 and 2, ensuring that the function handles the combination of positive and negative numbers correctly, effectively increasing the test coverage.

Scenario 4: Sorting a list with duplicate integers
Details:
  TestName: test_sort_list_with_duplicates
  Description: Checks if the quick sort algorithm correctly handles duplicate values within the input list.
Execution:
  Arrange: Prepare a list with duplicate integers, such as `[1, 2, 2, 3, 3, 3, 4, 4, 4, 4]`.
  Act: Call the `quick_sort` function with the list containing duplicates.
  Assert: Verify that the sorted list contains all duplicate elements in their correct sorted positions, maintaining the frequency of each element. Check this by comparing against `sorted()` applied to the same input.
Validation:
  Duplicate elements are a common scenario. This test ensures the function doesn't lose or misplace duplicates during sorting.

Scenario 5: Sorting a list with a single element
Details:
  TestName: test_sort_single_element_list
  Description: Checks the function's behavior with a list containing only one element.
Execution:
  Arrange: Create a list containing a single element, for example, `[5]`.
  Act: Call the `quick_sort` function with the single-element list.
  Assert: Assert that the returned list is identical to the input list (because a single-element list is already sorted).
Validation:
  This is a boundary condition test to verify the base case handling of the recursion in the quick sort implementation.

Scenario 6: Sorting an empty list
Details:
  TestName: test_sort_empty_list
  Description: Tests the function's response to an empty input list.
Execution:
  Arrange: Create an empty list `[]`.
  Act: Pass the empty list to the `quick_sort` function.
  Assert: Assert that the function returns an empty list.
Validation:
  This is another boundary condition test, ensuring the code gracefully handles empty input lists without errors.

Scenario 7: Sorting a list of floating-point numbers
Details:
  TestName: test_sort_floating_point_numbers
  Description: Verifies that the quick sort algorithm works correctly with floating-point numbers.
Execution:
  Arrange: Prepare a list of floating-point numbers, such as `[3.14, 1.618, 2.718, 0.0, 1.0]`.
  Act: Call the `quick_sort` function with the list of floating-point numbers.
  Assert: Check if the returned list is sorted in ascending order. Compare the output to the result of calling `sorted()` on the same input list.
Validation:
  This test confirms that the algorithm is applicable to and functions correctly with floating-point data, not just integers.

Scenario 8: Sorting a list that is already sorted
Details:
  TestName: test_sort_already_sorted_list
  Description: Tests the performance of the algorithm when the input is already sorted.
Execution:
  Arrange: Prepare a sorted list, such as `[1, 2, 3, 4, 5]`.
  Act: Call the `quick_sort` function with the already sorted list.
  Assert: Verify that the output list is still correctly sorted and is identical to the input list.
Validation:
  This tests a specific case to verify the efficiency of the algorithm, even in a scenario where no reordering is required. It helps ensure it doesn't degrade performance unnecessarily.

Scenario 9: Sorting a list in reverse order
Details:
  TestName: test_sort_reverse_sorted_list
  Description: Tests the algorithm's capability to sort a list given in reverse order.
Execution:
  Arrange: Prepare a list sorted in reverse order, such as `[5, 4, 3, 2, 1]`.
  Act: Call the `quick_sort` function with the reverse-sorted list.
  Assert: Assert that the output list is sorted in ascending order. Compare against the output of `sorted()` on the original list.
Validation:
  This tests a worst-case scenario for some sorting algorithms, ensuring quick sort handles the input effectively.

Scenario 10: Sorting a list with a large number of elements.
Details:
  TestName: test_sort_large_list
  Description: Tests the scalability and performance of quick sort with a larger input size.
Execution:
  Arrange: Generate a list containing a significant number of random integers (e.g., 1000 or more elements).
  Act: Call the `quick_sort` function with the generated large list.
  Assert: Verify the output is sorted correctly. It's crucial to measure the execution time and confirm that the algorithm efficiently sorts the large input. Compare against `sorted()` result.
Validation:
  This test validates the efficiency of the algorithm for large datasets and helps identify potential performance issues.

"""

# ********RoostGPT********
import pytest
from sorts.recursive_quick_sort import quick_sort
import random

class Test_RecursiveQuickSortQuickSort:
    @pytest.mark.valid
    def test_sort_positive_integers(self):
        data = [3, 1, 4, 1, 5, 9, 2, 6]
        sorted_data = quick_sort(data)
        assert sorted_data == sorted(data)

    @pytest.mark.valid
    def test_sort_negative_integers(self):
        data = [-3, -1, -4, -1, -5, -9, -2, -6]
        sorted_data = quick_sort(data)
        assert sorted_data == sorted(data)

    @pytest.mark.valid
    def test_sort_mixed_positive_negative_integers(self):
        data = [-2, 1, -5, 4, 0, -1, 3]
        sorted_data = quick_sort(data)
        assert sorted_data == sorted(data)

    @pytest.mark.valid
    def test_sort_list_with_duplicates(self):
        data = [1, 2, 2, 3, 3, 3, 4, 4, 4, 4]
        sorted_data = quick_sort(data)
        assert sorted_data == sorted(data)

    @pytest.mark.valid
    def test_sort_single_element_list(self):
        data = [5]
        sorted_data = quick_sort(data)
        assert sorted_data == data

    @pytest.mark.valid
    def test_sort_empty_list(self):
        data = []
        sorted_data = quick_sort(data)
        assert sorted_data == []

    @pytest.mark.valid
    def test_sort_floating_point_numbers(self):
        data = [3.14, 1.618, 2.718, 0.0, 1.0]
        sorted_data = quick_sort(data)
        assert sorted_data == sorted(data)

    @pytest.mark.valid
    def test_sort_already_sorted_list(self):
        data = [1, 2, 3, 4, 5]
        sorted_data = quick_sort(data)
        assert sorted_data == data

    @pytest.mark.valid
    def test_sort_reverse_sorted_list(self):
        data = [5, 4, 3, 2, 1]
        sorted_data = quick_sort(data)
        assert sorted_data == sorted(data)

    @pytest.mark.performance
    def test_sort_large_list(self):
        n = 1000  # TODO: Adjust the size if needed
        data = [random.randint(1, 10000) for _ in range(n)]  # Generates a list of random integer
        sorted_data = quick_sort(data)
        assert sorted_data == sorted(data)
