# ********RoostGPT********
"""
Test generated by RoostGPT for test pythonLangTest using AI Type Open AI and AI Model gpt-4o

ROOST_METHOD_HASH=exchange_sort_efca3f9a46
ROOST_METHOD_SIG_HASH=exchange_sort_915f5d2707


Scenario 1: Sorting an Already Sorted List
Details:
  TestName: test_sorted_list
  Description: This test verifies that the function correctly identifies an already sorted list and returns it unchanged, ensuring no unnecessary operations are performed.
Execution:
  Arrange: Prepare a list that is already sorted in ascending order, such as [1, 2, 3, 4, 5].
  Act: Invoke the exchange_sort function with the sorted list as the parameter.
  Assert: Check that the returned list is identical to the input list, confirming it remains [1, 2, 3, 4, 5].
Validation:
  Rationalize the importance of ensuring that the function can handle sorted lists efficiently, which is a common edge case in sorting algorithms.

Scenario 2: Sorting a Reverse Ordered List
Details:
  TestName: test_reverse_ordered_list
  Description: This test checks the function's ability to sort a list that is in completely reverse order, which is a worst-case scenario for many sorting algorithms.
Execution:
  Arrange: Prepare a list in descending order, such as [5, 4, 3, 2, 1].
  Act: Call the exchange_sort function with the reverse ordered list.
  Assert: Verify that the returned list is sorted in ascending order, [1, 2, 3, 4, 5].
Validation:
  Rationalize the importance of testing the function's performance and correctness in handling worst-case scenarios, ensuring robustness.

Scenario 3: Sorting a List with Negative Numbers
Details:
  TestName: test_negative_numbers
  Description: This test ensures that the function can correctly sort lists containing negative numbers, which can be a source of errors in sorting logic.
Execution:
  Arrange: Prepare a list with negative numbers, such as [-1, -2, -3].
  Act: Execute the exchange_sort function with the list of negative numbers.
  Assert: Confirm that the returned list is sorted in ascending order, [-3, -2, -1].
Validation:
  Rationalize the importance of verifying that the function handles negative numbers correctly, as they are a common part of numerical datasets.

Scenario 4: Sorting a List with Mixed Positive and Negative Numbers
Details:
  TestName: test_mixed_numbers
  Description: This test examines the function's ability to sort a list containing both positive and negative numbers, ensuring comprehensive sorting logic.
Execution:
  Arrange: Prepare a list with mixed positive and negative numbers, such as [0, 10, -2, 5, 3].
  Act: Invoke the exchange_sort function with the mixed list.
  Assert: Check that the returned list is sorted in ascending order, [-2, 0, 3, 5, 10].
Validation:
  Rationalize the importance of testing the function's ability to handle diverse numerical inputs, which is critical for real-world applications.

Scenario 5: Sorting an Empty List
Details:
  TestName: test_empty_list
  Description: This test verifies that the function correctly handles an empty list, returning it unchanged, which is an essential edge case.
Execution:
  Arrange: Prepare an empty list, [].
  Act: Call the exchange_sort function with the empty list.
  Assert: Ensure that the returned list is still empty, [].
Validation:
  Rationalize the importance of confirming that the function can gracefully handle empty inputs without errors, ensuring stability and reliability.

"""

# ********RoostGPT********
import pytest
from exchange_sort import exchange_sort

class Test_ExchangeSortExchangeSort:

    @pytest.mark.positive
    def test_sorted_list(self):
        # Arrange
        sorted_list = [1, 2, 3, 4, 5]
        
        # Act
        result = exchange_sort(sorted_list)
        
        # Assert
        assert result == [1, 2, 3, 4, 5], "The sorted list should remain unchanged."

    @pytest.mark.negative
    def test_reverse_ordered_list(self):
        # Arrange
        reverse_ordered_list = [5, 4, 3, 2, 1]
        
        # Act
        result = exchange_sort(reverse_ordered_list)
        
        # Assert
        assert result == [1, 2, 3, 4, 5], "The reverse ordered list should be sorted in ascending order."

    @pytest.mark.negative
    def test_negative_numbers(self):
        # Arrange
        negative_numbers_list = [-1, -2, -3]
        
        # Act
        result = exchange_sort(negative_numbers_list)
        
        # Assert
        assert result == [-3, -2, -1], "The list with negative numbers should be sorted in ascending order."

    @pytest.mark.positive
    def test_mixed_numbers(self):
        # Arrange
        mixed_numbers_list = [0, 10, -2, 5, 3]
        
        # Act
        result = exchange_sort(mixed_numbers_list)
        
        # Assert
        assert result == [-2, 0, 3, 5, 10], "The list with mixed numbers should be sorted in ascending order."

    @pytest.mark.edge
    def test_empty_list(self):
        # Arrange
        empty_list = []
        
        # Act
        result = exchange_sort(empty_list)
        
        # Assert
        assert result == [], "The empty list should remain unchanged."
