# ********RoostGPT********
"""
Test generated by RoostGPT for test testingGemini-1 using AI Type Gemini AI and AI Model gemini-2.0-flash-lite

ROOST_METHOD_HASH=bucket_sort_577a38ca8e
ROOST_METHOD_SIG_HASH=bucket_sort_bb20308c75


Scenario 1: Sorting a list of positive integers
Details:
  TestName: test_bucket_sort_positive_integers
  Description: Verifies that bucket_sort correctly sorts a list containing only positive integers. The test checks if the output is a sorted version of the input list.
Execution:
  Arrange: Create a list of positive integers, e.g., `my_list = [5, 2, 8, 1, 9]`.
  Act: Call `bucket_sort(my_list)` with the created list and default `bucket_count`.
  Assert: Assert that the returned list is equal to the sorted version of `my_list` using `sorted(my_list)`.
Validation:
  This test ensures the core functionality of bucket sort works correctly with a common type of input. The success of this test demonstrates that the sorting logic within the buckets and the merging of buckets are functioning as expected.

Scenario 2: Sorting a list of negative integers
Details:
  TestName: test_bucket_sort_negative_integers
  Description: Tests if bucket_sort sorts a list containing only negative integers. The test checks if the output is a sorted version of the input list.
Execution:
  Arrange: Create a list of negative integers, e.g., `my_list = [-5, -2, -8, -1, -9]`.
  Act: Call `bucket_sort(my_list)` with the created list and default `bucket_count`.
  Assert: Assert that the returned list is equal to the sorted version of `my_list` using `sorted(my_list)`.
Validation:
  This test focuses on handling negative values, ensuring that the algorithm correctly places negative numbers into their respective buckets and sorts them accordingly. It's crucial for the correct functionality of the function.

Scenario 3: Sorting a list containing both positive and negative integers
Details:
  TestName: test_bucket_sort_mixed_integers
  Description: Checks the correct sorting of a list that contains both positive and negative integers.  This test validates the algorithm's capability to handle the full range of integer values.
Execution:
  Arrange: Create a list with mixed positive and negative integers, e.g., `my_list = [-5, 2, -8, 1, 0, 9, -1]`.
  Act: Call `bucket_sort(my_list)` with the created list and default `bucket_count`.
  Assert: Assert that the returned list is equal to the sorted version of `my_list` using `sorted(my_list)`.
Validation:
  This scenario tests the robustness of the algorithm to ensure that it correctly handles both positive and negative values, and their relative order is maintained after sorting.

Scenario 4: Sorting a list of floating-point numbers
Details:
  TestName: test_bucket_sort_floating_point_numbers
  Description: Verifies the functionality of bucket_sort when presented with floating-point numbers. It assesses the correct handling and sorting of decimal values.
Execution:
  Arrange: Create a list of floating-point numbers, e.g., `my_list = [5.2, 2.1, 8.8, 1.5, 9.9]`.
  Act: Call `bucket_sort(my_list)` with the created list and default `bucket_count`.
  Assert: Assert that the returned list is equal to the sorted version of `my_list` using `sorted(my_list)`.
Validation:
  This test validates the function's ability to handle floating-point values correctly, ensuring the correct placement and sorting within buckets when dealing with decimal numbers.

Scenario 5: Sorting a list with duplicate values
Details:
  TestName: test_bucket_sort_duplicate_values
  Description: Validates bucket_sort's ability to handle lists containing duplicate values, verifying the correct ordering of repeated elements.
Execution:
  Arrange: Create a list with duplicate values, e.g., `my_list = [5, 2, 5, 1, 2]`.
  Act: Call `bucket_sort(my_list)` with the created list and default `bucket_count`.
  Assert: Assert that the returned list is equal to the sorted version of `my_list` using `sorted(my_list)`.
Validation:
  This test checks the stability of the sorting algorithm, ensuring that the relative order of duplicate elements is preserved, which is a desirable characteristic for any sorting algorithm.

Scenario 6: Sorting an empty list
Details:
  TestName: test_bucket_sort_empty_list
  Description: Tests the behavior of bucket_sort when given an empty list as input. It verifies that an empty list returns an empty list.
Execution:
  Arrange: Create an empty list, `my_list = []`.
  Act: Call `bucket_sort(my_list)` with the empty list.
  Assert: Assert that the returned list is an empty list, i.e., `bucket_sort(my_list) == []`.
Validation:
  This test case validates the edge case of an empty input list.  It checks the function's resilience and that it handles empty inputs gracefully, preventing potential errors.

Scenario 7: Sorting a list with a single element
Details:
  TestName: test_bucket_sort_single_element_list
  Description: Tests the function with a list that contains only one element.
Execution:
  Arrange: Create a single-element list, `my_list = [5]`.
  Act: Call `bucket_sort(my_list)`.
  Assert: Assert that the returned list is equal to the original list: `bucket_sort(my_list) == [5]`.
Validation:
  This is another edge case test. It ensures the algorithm correctly processes lists with only one item.

Scenario 8: Using a custom bucket_count
Details:
  TestName: test_bucket_sort_custom_bucket_count
  Description: Tests the function by specifying a different bucket_count. The test checks if the output is a sorted version of the input list.
Execution:
  Arrange: Create a list of integers, `my_list = [5, 2, 8, 1, 9]`. Set a different bucket count, `bucket_count = 5`.
  Act: Call `bucket_sort(my_list, bucket_count)` with the list and specified bucket count.
  Assert: Assert that the returned list is equal to the sorted version of `my_list` using `sorted(my_list)`.
Validation:
  This validates that the `bucket_count` parameter correctly influences the behavior of the sorting algorithm.  It also checks if the function can work correctly when the number of buckets is changed.

Scenario 9: Input list with a large range of values.
Details:
  TestName: test_bucket_sort_large_range
  Description: Tests bucket sort with a list containing a large range of numbers.
Execution:
  Arrange: Create a list `my_list` with a large range of integer values, for example, from -1000 to 1000, using `my_list = list(range(-1000, 1001))`.
  Act: Call `bucket_sort(my_list)` with the list.
  Assert: Assert that the result is equal to `sorted(my_list)`.
Validation:
  This test ensures the function can handle lists where the range between the minimum and maximum values is considerable. It verifies that the bucket size calculation works correctly in this situation.

Scenario 10: Bucket count equals 1
Details:
  TestName: test_bucket_sort_bucket_count_one
  Description: Tests bucket sort with a bucket_count of 1.
Execution:
  Arrange: Create a list of integers `my_list = [5, 2, 8, 1, 9]`. Set `bucket_count = 1`.
  Act: Call `bucket_sort(my_list, bucket_count)`.
  Assert: Assert that the result is equal to `sorted(my_list)`.
Validation:
  This edge case tests to confirm that when bucket_count is 1, the algorithm still produces the correct output (essentially behaving like a less efficient sort due to all elements ending up in a single bucket).

"""

# ********RoostGPT********
from __future__ import annotations
from doctest import testmod
import pytest
from sorts.bucket_sort import bucket_sort


class Test_BucketSortBucketSort:

    @pytest.mark.valid
    def test_bucket_sort_positive_integers(self):
        my_list = [5, 2, 8, 1, 9]
        assert bucket_sort(my_list) == sorted(my_list)

    @pytest.mark.valid
    def test_bucket_sort_negative_integers(self):
        my_list = [-5, -2, -8, -1, -9]
        assert bucket_sort(my_list) == sorted(my_list)

    @pytest.mark.valid
    def test_bucket_sort_mixed_integers(self):
        my_list = [-5, 2, -8, 1, 0, 9, -1]
        assert bucket_sort(my_list) == sorted(my_list)

    @pytest.mark.valid
    def test_bucket_sort_floating_point_numbers(self):
        my_list = [5.2, 2.1, 8.8, 1.5, 9.9]
        assert bucket_sort(my_list) == sorted(my_list)

    @pytest.mark.valid
    def test_bucket_sort_duplicate_values(self):
        my_list = [5, 2, 5, 1, 2]
        assert bucket_sort(my_list) == sorted(my_list)

    @pytest.mark.valid
    def test_bucket_sort_empty_list(self):
        my_list = []
        assert bucket_sort(my_list) == []

    @pytest.mark.valid
    def test_bucket_sort_single_element_list(self):
        my_list = [5]
        assert bucket_sort(my_list) == [5]

    @pytest.mark.valid
    def test_bucket_sort_custom_bucket_count(self):
        my_list = [5, 2, 8, 1, 9]
        bucket_count = 5
        assert bucket_sort(my_list, bucket_count) == sorted(my_list)

    @pytest.mark.valid
    def test_bucket_sort_large_range(self):
        my_list = list(range(-1000, 1001))
        assert bucket_sort(my_list) == sorted(my_list)

    @pytest.mark.valid
    def test_bucket_sort_bucket_count_one(self):
        my_list = [5, 2, 8, 1, 9]
        bucket_count = 1
        assert bucket_sort(my_list, bucket_count) == sorted(my_list)
