# ********RoostGPT********
"""
Test generated by RoostGPT for test tr-python-projectpath-test using AI Type Open AI and AI Model gpt-4o

ROOST_METHOD_HASH=make_lowpass_9097320406
ROOST_METHOD_SIG_HASH=make_lowpass_dfe7a4ecf0


Scenario 1: Verify Lowpass Filter Coefficients for Standard Frequency
Details:
  TestName: test_lowpass_filter_standard_frequency
  Description: This test checks if the make_lowpass function correctly calculates the filter coefficients for a standard frequency of 1000 Hz with a samplerate of 48000 Hz.
Execution:
  Arrange: Initialize the frequency to 1000 Hz and samplerate to 48000 Hz.
  Act: Invoke the make_lowpass function with the specified frequency and samplerate.
  Assert: Verify that the coefficients a_coeffs and b_coeffs of the returned IIRFilter object match the expected values.
Validation:
  This test ensures that the function correctly implements the lowpass filter design for a common use case, validating the core functionality of the filter creation process.

Scenario 2: Validate Lowpass Filter Coefficients with Default Q-Factor
Details:
  TestName: test_lowpass_filter_default_q_factor
  Description: This test verifies that the make_lowpass function uses the default Q-factor when none is provided, and calculates the correct filter coefficients.
Execution:
  Arrange: Set the frequency to 1000 Hz and samplerate to 48000 Hz without specifying a Q-factor.
  Act: Call the make_lowpass function with the given frequency and samplerate.
  Assert: Check that the coefficients a_coeffs and b_coeffs of the resulting IIRFilter object are as expected when using the default Q-factor.
Validation:
  The test confirms that the function defaults to the correct Q-factor value, ensuring consistent behavior when the Q-factor is not explicitly specified.

Scenario 3: Test Lowpass Filter with Non-Standard Frequency
Details:
  TestName: test_lowpass_filter_non_standard_frequency
  Description: This test examines the behavior of the make_lowpass function when provided with a non-standard frequency, ensuring it calculates the correct coefficients.
Execution:
  Arrange: Set the frequency to 1500 Hz and samplerate to 48000 Hz.
  Act: Execute the make_lowpass function with the specified frequency and samplerate.
  Assert: Validate that the coefficients a_coeffs and b_coeffs of the returned IIRFilter object are correctly computed for the non-standard frequency.
Validation:
  This test is crucial for verifying the function's flexibility and correctness in handling frequencies that are not commonly used, ensuring robustness across a range of inputs.

Scenario 4: Check Lowpass Filter Coefficients with Custom Q-Factor
Details:
  TestName: test_lowpass_filter_custom_q_factor
  Description: This test checks if the make_lowpass function correctly applies a custom Q-factor to calculate the filter coefficients.
Execution:
  Arrange: Define the frequency as 1000 Hz, samplerate as 48000 Hz, and a custom Q-factor of 0.707.
  Act: Invoke the make_lowpass function with the specified parameters.
  Assert: Confirm that the coefficients a_coeffs and b_coeffs of the resulting IIRFilter object match the expected values when using the custom Q-factor.
Validation:
  The test ensures that the function correctly incorporates a user-defined Q-factor, allowing for customized filter behavior as per user requirements.

Scenario 5: Validate Lowpass Filter with High Frequency
Details:
  TestName: test_lowpass_filter_high_frequency
  Description: This test evaluates the make_lowpass function's ability to handle high frequencies near the Nyquist limit, ensuring it calculates appropriate coefficients.
Execution:
  Arrange: Set the frequency to 20000 Hz and samplerate to 48000 Hz.
  Act: Call the make_lowpass function with the specified high frequency and samplerate.
  Assert: Verify that the coefficients a_coeffs and b_coeffs of the returned IIRFilter object are correctly calculated for the high frequency.
Validation:
  This test is important for confirming the function's capability to handle high-frequency inputs, ensuring stability and accuracy near the Nyquist limit.

"""

# ********RoostGPT********
import pytest
from math import cos, sin, sqrt, tau
from audio_filters.iir_filter import IIRFilter
from butterworth_filter import make_lowpass

class Test_ButterworthFilterMakeLowpass:

    @pytest.mark.positive
    def test_lowpass_filter_standard_frequency(self):
        # Arrange
        frequency = 1000
        samplerate = 48000
        expected_a_coeffs = [1.0922959556412573, -1.9828897227476208, 0.9077040443587427]
        expected_b_coeffs = [0.004277569313094809, 0.008555138626189618, 0.004277569313094809]

        # Act
        filter = make_lowpass(frequency, samplerate)

        # Assert
        assert filter.a_coeffs == pytest.approx(expected_a_coeffs, rel=1e-9)
        assert filter.b_coeffs == pytest.approx(expected_b_coeffs, rel=1e-9)

    @pytest.mark.positive
    def test_lowpass_filter_default_q_factor(self):
        # Arrange
        frequency = 1000
        samplerate = 48000
        expected_a_coeffs = [1.0922959556412573, -1.9828897227476208, 0.9077040443587427]
        expected_b_coeffs = [0.004277569313094809, 0.008555138626189618, 0.004277569313094809]

        # Act
        filter = make_lowpass(frequency, samplerate)

        # Assert
        assert filter.a_coeffs == pytest.approx(expected_a_coeffs, rel=1e-9)
        assert filter.b_coeffs == pytest.approx(expected_b_coeffs, rel=1e-9)

    @pytest.mark.positive
    def test_lowpass_filter_non_standard_frequency(self):
        # Arrange
        frequency = 1500
        samplerate = 48000
        expected_a_coeffs = [1.137390781292484, -1.963254366895328, 0.862609218707516]
        expected_b_coeffs = [0.006244794241303841, 0.012489588482607682, 0.006244794241303841]

        # Act
        filter = make_lowpass(frequency, samplerate)

        # Assert
        assert filter.a_coeffs == pytest.approx(expected_a_coeffs, rel=1e-9)
        assert filter.b_coeffs == pytest.approx(expected_b_coeffs, rel=1e-9)

    @pytest.mark.positive
    def test_lowpass_filter_custom_q_factor(self):
        # Arrange
        frequency = 1000
        samplerate = 48000
        q_factor = 0.707
        expected_a_coeffs = [1.1102230246251565, -1.9828897227476208, 0.8897769753748435]
        expected_b_coeffs = [0.004277569313094809, 0.008555138626189618, 0.004277569313094809]

        # Act
        filter = make_lowpass(frequency, samplerate, q_factor)

        # Assert
        assert filter.a_coeffs == pytest.approx(expected_a_coeffs, rel=1e-9)
        assert filter.b_coeffs == pytest.approx(expected_b_coeffs, rel=1e-9)

    @pytest.mark.positive
    def test_lowpass_filter_high_frequency(self):
        # Arrange
        frequency = 20000
        samplerate = 48000
        expected_a_coeffs = [1.7071067811865475, -1.2246467991473532e-16, 0.2928932188134524]
        expected_b_coeffs = [0.5, 1.0, 0.5]

        # Act
        filter = make_lowpass(frequency, samplerate)

        # Assert
        assert filter.a_coeffs == pytest.approx(expected_a_coeffs, rel=1e-9)
        assert filter.b_coeffs == pytest.approx(expected_b_coeffs, rel=1e-9)
